### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by willingc** [jupyterhub/batchspawner#51]
It's been a long while since we've had a batchspawner release. With the release of JupyterHub 0.8, we should create a more up-to-date release of batchspawner.

- [x] Review 3 pending PRs
- [x] Update changelog
- [x] Create beta release

I know folks are very busy. If you are willing and able to help review and the open PRs and test the beta release, please +1 this issue (@minrk, @zonca, @mbmilligan, @willfurnass, @yuvipanda, and others that may be interested) . Thanks. 

cc @DeepHorizons

**Comment by mbmilligan** [comment]
Agreed, excellent idea! Unfortunately, according to Travis, it doesn't currently **work** with JupyterHub 0.8, so that definitely needs to get resolved before the release, too. (ProfilesSpawner is also broken by 0.8, incidentally, so I've been looking into the fix since https://github.com/jupyterhub/wrapspawner/issues/11 alerted me to the problem.)

**Comment by DeepHorizons** [comment]
I'm using SlurmSpawner with Jupyterhub 0.8, seems to be working just fine. I'll see if I can find out why it's failing the Travis builds.

**Comment by mbmilligan** [comment]
@DeepHorizons that's curious, do you possibly have any local patches applied to your `batchspawner` installation? I've been doing some work to get the tests running in the `ci-update` branch. I'm finding that some attributes have been moved around such that I don't think `batchspawner` can possibly be working as-is with Jupyterhub 0.8. Right now it's failing because `self.user.server` is no longer a thing, and that's used all over the start/stop coroutines.

**Comment by DeepHorizons** [comment]
Na, no local patches. `self.user.server` is deprecated, but not removed. Both `self.port` and `self.user.server.port` set the same variable under the hood, one just issues a warning. I have been pulling in other commits but nothing fundamentally different. I haven't dived into the tests so I'm not sure whats failing but this is working currently with my setup with Jupyterhub 0.8.0.

**Comment by DeepHorizons** [comment]
So I finally had time to come back to this and I 100% lied when I said I didn't have any local patches. I made #55 which makes batchspawner work under 0.8 and fixes the tests.

After that, the PR's to pull in would be #43 amd #45. I'll then fix #32 and we can get that merged in too.

**Comment by rcthomas** [comment]
FWIW a data point: @DeepHorizons suggestions seemed to work for me on a fork where I just merged all that stuff in.  No additional points beyond that.

Not extensively tested but I'm able to start jobs using a modified SlurmSpawner (we have to ssh to the submit node and do things remotely).

**Comment by DeepHorizons** [comment]
Any update on this? I'm starting to get back into the swing of things and saw a new version was still not released. Anything I can do to help?

**Comment by mbmilligan** [comment]
Ok, I've finally had time to finish up reviewing the outstanding issues and PRs and gotten the CI testing working again. I think we're finally in good shape for a release. #32 I want to postpone to after a release, and #58 I am going to propose to the Jupyterhub devs as a potentially generally useful feature. 

Do those reading this have any opinions about version numbering? My original idea was to base the version number off the latest supported Jupyterhub release. It looks like some Jupyterhub extensions do that, and others just have an incrementing count. None appear to have pulled the trigger on putting out a 1.0 release. 

Also, are we okay with beta releases in Github, or would PyPI pre-release uploads also be useful?

**Comment by rcthomas** [comment]
I endorse that #58 would be generically useful for all the reasons pointed out in that thread.  No strong opinions on either of the other two questions.

**Comment by DeepHorizons** [comment]
PR stuff sounds good to me.

I think following the Jupyterhub versioning is a good idea since this is ultimately linked to that. If we need to release a new version we can just add a new decimal (ie, `0.8.2.1`).

While PyPI pre-releases would be helpful, just doing betas on github should be just fine for me.

**Comment by minrk** [comment]
I'd prefer to not link to jupyterhub versioning, and express dependencies in setup.py. While there may need to be occasional fixes for new jupyterhub releases, maintaining compatibility back a release or two shouldn't generally be an issue.

**Comment by mbmilligan** [comment]
Ok, not seeing any additional feedback (and now that I've gotten a paper out the door and I have more time to look at this) - I'll go ahead and cut a RC version today. Regarding versions, let's call it 0.8 to reinforce the impression that this release works with jhub 0.8, but we'll not regard that a formal linkage. We currently test functionality going back to jhub 0.5, and I'll put that relationship in the requirements.

**Comment by mbmilligan** [comment]
[0.8.0rc0](https://github.com/jupyterhub/batchspawner/releases/tag/0.8.0rc0) has been tagged. Feedback welcome. Some things to note before tagging a production release:

* Still need to write up a changelog
* Figure out why tests are suddenly failing for Python 3.3 (i.e. why is `asyncio` not getting installed in the testing environment, when it worked in the previous commit?)

**Comment by rkdarst** [comment]
A release would be nice...

to help that, I tried investigating the build failures.

* On 2017-09-04, tornado dropped 3.3 support
* On 2017-07-19, jupyterhub dropped 3.3 support
* On 2018-03-01, jupyturhub added asyncio dep (this is irrelevent)

I guess the problem is the first one - except the pin to `tornado<5.0` would seem to handle it. I can't find the exact problem, but I also can't find any dependency that actually pulls in asyncio or replacement on 3.3 (as in, how did it even work on 3.3 before?).  I guess the simple solution is to raise supported python version, but this is kind of unelegant.

I wish I could be of more help...

I'm using latest in production using Slurm and it works.

**Comment by mbmilligan** [comment]
Ok, figured it out, Travis tests are fixed as of PR #69 

We also have a reasonable Changelog in the README now thanks to #67 and I've fixed a couple of quick non-invasive issues. Last call to nominate issues urgently needing fixes before cutting the release. If I don't hear otherwise I'll tag the release version this weekend or Monday.

After that we can start tackling templates and dynamic ports and so on, hooray!

**Comment by mbmilligan** [comment]
Batchspawner 0.8.0 is tagged and released.

Please give [pip install batchspawner](https://pypi.org/project/batchspawner/) a spin and report any issues!
